<!-- not to be executed as it will give wrong result-->
<?php if (false && $this->engineStatus()) : ?>
    <script type="text/javascript">
        var searchInput = document.getElementById("search_mini_form");

        <?php if(Mage::registry("tagsList") != '') : ?>
        var input = document.createElement("input");
        input.name = "tagsList";
        input.type = "hidden";
        input.value = "<?php echo Mage::registry("tagsList"); ?>";

        searchInput.appendChild(input);
        <?php endif; ?>

        <?php if(Mage::registry("catPaths") && Mage::registry("catPaths") != "") : ?>
        var input2 = document.createElement("input");
        input2.name = "catPaths";
        input2.type = "hidden";
        input2.value = '<?php echo Mage::registry("catPaths"); ?>';

        searchInput.appendChild(input2);
        <?php endif; ?>


        <?php if(Mage::registry("prodCountNow") != '') : ?>
        var input3 = document.createElement("input");
        input3.name = "ct";
        input3.type = "hidden";
        input3.value = <?php echo Mage::registry("prodCountNow"); ?>;

        searchInput.appendChild(input3);
        <?php endif; ?>
    </script>
<?php endif; ?>