<?php
// Passing passback if received from server
if(Mage::registry("expId") && !Mage::registry("passback")) { ?>
    <script type="text/javascript">
        window._caiExistingPage = '<?php echo Mage::registry("expId") ?>';
    </script>
<?php
}
if (Mage::registry("passback")) { ?>
    <script type="text/javascript">
        //<![CDATA[
        window._caiapi = window._caiapi || [];
        window._caiExistingPage = '<?php echo Mage::registry("passback")["expId"] ?>';
        _caiapi.push(['trackExperiment', <?php echo Mage::helper('core')->jsonEncode(Mage::registry("passback")) ?>]);
        //]]>
    </script>
    <?php
}
?>

<script type="text/javascript">
    //<![CDATA[
    window._caity = <?php echo $this->engineStatus() ? '"clistpage"' : '"category"' ?>;
    //]]>
</script>
